[build-system]
requires = ["setuptools>=44", "wheel", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "chardet/version.py"
write_to_template = "__version__ = '4.0.0'\nVERSION = __version__.split('.')"
